development: &defaults
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  pool: 4
  reconnect: true
  reaping_frequency: 10
  database: nutrigemeas_development

test:
  <<: *defaults
  database: nutrigemeas_test

production:
  <<: *defaults
  database: nutrigemeas_production
